/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediasIndexRouteImport } from './routes/medias.index'
import { Route as DiscoverIndexRouteImport } from './routes/discover.index'
import { Route as AlbumsIndexRouteImport } from './routes/albums.index'
import { Route as ItemIdIndexRouteImport } from './routes/item.$id.index'
import { Route as AlbumIdIndexRouteImport } from './routes/album.$id.index'

const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediasIndexRoute = MediasIndexRouteImport.update({
  id: '/medias/',
  path: '/medias/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdIndexRoute = ItemIdIndexRouteImport.update({
  id: '/item/$id/',
  path: '/item/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdIndexRoute = AlbumIdIndexRouteImport.update({
  id: '/album/$id/',
  path: '/album/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/albums/': typeof AlbumsIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/medias/': typeof MediasIndexRoute
  '/album/$id/': typeof AlbumIdIndexRoute
  '/item/$id/': typeof ItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/albums': typeof AlbumsIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/medias': typeof MediasIndexRoute
  '/album/$id': typeof AlbumIdIndexRoute
  '/item/$id': typeof ItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/counter': typeof CounterRoute
  '/albums/': typeof AlbumsIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/medias/': typeof MediasIndexRoute
  '/album/$id/': typeof AlbumIdIndexRoute
  '/item/$id/': typeof ItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/counter'
    | '/albums/'
    | '/discover/'
    | '/medias/'
    | '/album/$id/'
    | '/item/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/counter'
    | '/albums'
    | '/discover'
    | '/medias'
    | '/album/$id'
    | '/item/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/counter'
    | '/albums/'
    | '/discover/'
    | '/medias/'
    | '/album/$id/'
    | '/item/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CounterRoute: typeof CounterRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  MediasIndexRoute: typeof MediasIndexRoute
  AlbumIdIndexRoute: typeof AlbumIdIndexRoute
  ItemIdIndexRoute: typeof ItemIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medias/': {
      id: '/medias/'
      path: '/medias'
      fullPath: '/medias/'
      preLoaderRoute: typeof MediasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id/': {
      id: '/item/$id/'
      path: '/item/$id'
      fullPath: '/item/$id/'
      preLoaderRoute: typeof ItemIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id/': {
      id: '/album/$id/'
      path: '/album/$id'
      fullPath: '/album/$id/'
      preLoaderRoute: typeof AlbumIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CounterRoute: CounterRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  MediasIndexRoute: MediasIndexRoute,
  AlbumIdIndexRoute: AlbumIdIndexRoute,
  ItemIdIndexRoute: ItemIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
